name: Keepalive Workflow

on:
  schedule:
    # Runs at 00:00 UTC on the first day of every month
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Run keepalive
        uses: gautamkrishnar/keepalive-workflow@2.0.10
